// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrchestrationPlatform.Infrastructure.Persistence.Contexts;

#nullable disable

namespace OrchestrationPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrchestrationWriteDbContext))]
    [Migration("20260611143123_AddotherOperationtype_v3")]
    partial class AddotherOperationtype_v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orchestration")
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.InstalledSoftware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InstalledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstalledName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("InstalledVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OperatingSystemHostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrchestrationOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RemovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SoftwarePackageVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OperatingSystemHostId")
                        .HasDatabaseName("IX_InstalledSoftwares_OperatingSystemHostId");

                    b.HasIndex("OrchestrationOperationId")
                        .IsUnique()
                        .HasDatabaseName("UX_InstalledSoftwares_OrchestrationOperationId");

                    b.HasIndex("SoftwarePackageVersionId")
                        .HasDatabaseName("IX_InstalledSoftwares_SoftwarePackageVersionId");

                    b.HasIndex("OperatingSystemHostId", "InstalledName")
                        .IsUnique()
                        .HasDatabaseName("UX_InstalledSoftwares_Host_InstalledName_Active")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("InstalledSoftwares", "orchestration");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.OperatingSystemHost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Architecture")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastConnectionError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OperatingSystemFamily")
                        .HasColumnType("int");

                    b.Property<string>("OperatingSystemVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SshKeyPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SshPort")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_OperatingSystemHosts_Name");

                    b.HasIndex("IpAddress", "SshPort")
                        .IsUnique()
                        .HasDatabaseName("UX_OperatingSystemHosts_IpAddress_SshPort")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("OperatingSystemHosts", "orchestration");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.OperationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoggedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrchestrationOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Level")
                        .HasDatabaseName("IX_OperationLogs_Level");

                    b.HasIndex("OrchestrationOperationId", "LoggedAtUtc")
                        .HasDatabaseName("IX_OperationLogs_InstallOperationId_LoggedAtUtc");

                    b.ToTable("OperationLogs", "orchestration");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.OrchestrationOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("int");

                    b.Property<string>("ExternalWorkflowId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OperatingSystemHostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<string>("PackageNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SoftwarePackageVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VersionSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("RequestedAtUtc")
                        .HasDatabaseName("IX_OrchestrationOperations_RequestedAtUtc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_OrchestrationOperations_Status");

                    b.HasIndex("OperatingSystemHostId", "RequestedAtUtc")
                        .HasDatabaseName("IX_OrchestrationOperations_HostId_RequestedAtUtc");

                    b.HasIndex("SoftwarePackageVersionId", "OperatingSystemHostId")
                        .HasDatabaseName("IX_OrchestrationOperations_PackageVersionId_HostId");

                    b.ToTable("OrchestrationOperations", "orchestration");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.PackageArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Sha256Hash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("SoftwarePackageVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SoftwarePackageVersionId")
                        .IsUnique()
                        .HasDatabaseName("UX_PackageArtifacts_SoftwarePackageVersionId");

                    b.HasIndex("BucketName", "ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("UX_PackageArtifacts_BucketName_ObjectKey")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("PackageArtifacts", "orchestration");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.SoftwarePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_SoftwarePackages_Name")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("SoftwarePackages", "orchestration");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.SoftwarePackageVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Architecture")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OperatingSystemFamily")
                        .HasColumnType("int");

                    b.Property<string>("OperatingSystemVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PackageType")
                        .HasColumnType("int");

                    b.Property<Guid>("SoftwarePackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SoftwarePackageId", "Version", "PackageType", "OperatingSystemFamily", "OperatingSystemVersion", "Architecture")
                        .IsUnique()
                        .HasDatabaseName("UX_SoftwarePackageVersions_UniqueVersion")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("SoftwarePackageVersions", "orchestration");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.InstalledSoftware", b =>
                {
                    b.HasOne("OrchestrationPlatform.Domain.Entities.OperatingSystemHost", "OperatingSystemHost")
                        .WithMany("InstalledSoftwares")
                        .HasForeignKey("OperatingSystemHostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrchestrationPlatform.Domain.Entities.OrchestrationOperation", "OrchestrationOperation")
                        .WithMany()
                        .HasForeignKey("OrchestrationOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrchestrationPlatform.Domain.Entities.SoftwarePackageVersion", "SoftwarePackageVersion")
                        .WithMany("InstalledSoftwares")
                        .HasForeignKey("SoftwarePackageVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OperatingSystemHost");

                    b.Navigation("OrchestrationOperation");

                    b.Navigation("SoftwarePackageVersion");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.OperationLog", b =>
                {
                    b.HasOne("OrchestrationPlatform.Domain.Entities.OrchestrationOperation", "OrchestrationOperation")
                        .WithMany("Logs")
                        .HasForeignKey("OrchestrationOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrchestrationOperation");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.OrchestrationOperation", b =>
                {
                    b.HasOne("OrchestrationPlatform.Domain.Entities.OperatingSystemHost", "OperatingSystemHost")
                        .WithMany("OrchestrationOperations")
                        .HasForeignKey("OperatingSystemHostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrchestrationPlatform.Domain.Entities.SoftwarePackageVersion", "SoftwarePackageVersion")
                        .WithMany("OrchestrationOperations")
                        .HasForeignKey("SoftwarePackageVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OperatingSystemHost");

                    b.Navigation("SoftwarePackageVersion");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.PackageArtifact", b =>
                {
                    b.HasOne("OrchestrationPlatform.Domain.Entities.SoftwarePackageVersion", "SoftwarePackageVersion")
                        .WithOne("Artifact")
                        .HasForeignKey("OrchestrationPlatform.Domain.Entities.PackageArtifact", "SoftwarePackageVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SoftwarePackageVersion");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.SoftwarePackageVersion", b =>
                {
                    b.HasOne("OrchestrationPlatform.Domain.Entities.SoftwarePackage", "SoftwarePackage")
                        .WithMany("Versions")
                        .HasForeignKey("SoftwarePackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SoftwarePackage");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.OperatingSystemHost", b =>
                {
                    b.Navigation("InstalledSoftwares");

                    b.Navigation("OrchestrationOperations");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.OrchestrationOperation", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.SoftwarePackage", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("OrchestrationPlatform.Domain.Entities.SoftwarePackageVersion", b =>
                {
                    b.Navigation("Artifact");

                    b.Navigation("InstalledSoftwares");

                    b.Navigation("OrchestrationOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
